## What is Numpy
> ###  NumPy is a Python package.
> ### It stands for 'Numerical Python'.


## Why Use Numpy for Machine learning

> ###  . In Machine learning alograthim is applied on numbers
> ### . For Example:
> ### . So When we use image detection it first convert image to numbers
> ### . Than apply Alogrithim using python list to store data is inefficent




## Numpy vs Python List
> ###  . Fast Process 
> ###   .Use Less Memory to Store data
> ###  . Convient

## installation
> ### . pip install numpy 


# Part 1

## Here we explain some function of NumPy Array:

> ###  . 1) How to create one and multidimensional array?
> ###  . 2) How to check the type & data type of array?
> ###  . 3) How to check the shape & size of the array?
> ###  . 4) How to check dimensions of an array?

In [1]:

import numpy as np 

In [3]:
# How to create NumPy Array ?
# One Dimenstion Array 

arr_1d =np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


numpy.ndarray

In [4]:
# checking dimension
arr_1d.ndim

1

In [5]:
# checking type of array 
type(arr_1d)


numpy.ndarray

In [19]:
# Two Dimenstion Array 
# [[]] double square bracket

arr_2d=np.array([[1,2,3,4],[2,3,4,5,]])

print(arr_2d)

[[1 2 3 4]
 [2 3 4 5]]


In [20]:
arr_2d.ndim # checking Dimenstion 

2

In [21]:
arr_1d.size # number of elements inside 1d_array

4

In [22]:
arr_2d.size # number of elements inside 2d_array

8

In [23]:
# shape returns number of columns and rows in array
arr_2d.shape 

# 2 row and 4 columns , 


(2, 4)

In [25]:
# type of data type in array

arr_2d.dtype

dtype('int64')