## Here we describe Python Functions:
> ### . 1) np.ones() 
> ### . 2) np.zeros() 
> ### . 3) np.empty() 


In [6]:
import numpy as np
# Creating two dimenstion array 

arr_2d=np.array([[1,1,1],[1,1,1],[1,1,1]])
arr_2d

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [7]:
# instead of putting manullay we can put it using build in function in np modules
# one dimenstion
arr_1s=np.ones(5)
print(arr_1s)

[1. 1. 1. 1. 1.]


In [8]:
arr_1s.dtype

dtype('float64')

In [9]:
# two dimenstion
arr_ones=np.ones((3,4))# first rows and than coloumns
print(arr_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
# two dimenstion with data type
a_ones=np.ones((3,5),dtype=int) # 3 rows and 5 columns 
print(a_ones)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [11]:
# two dimenstion with data type int

arr_zeros=np.zeros((4,5),dtype=int) # 4 rows and 5 columns
print(arr_zeros)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [12]:
# two dimenstion with data type bool
ar_zeros=np.zeros((4,3),dtype=bool)
ar_zeros

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [13]:
arr_zeros=np.zeros((4,3),dtype=str)
arr_zeros

array([['', '', ''],
       ['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [14]:
# empty string == 0 === False in python