## Here we describe Python Functions:
> ### . 1) np.arange() 
> ### . 2) np.linspace() 
> ### . 3) np.reshape() 
> ### . 4) np.ravel() 
> ### . 5) np.flatten() 
> ### . 6) np.transpose() 

In [1]:
import numpy as np

# arrange()


In [4]:
# np.arrange(start,end,steps)

arr_1d=np.arange(1,13)

print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [6]:
odd_arr=np.arange(1,13,2)
print(odd_arr)

[ 1  3  5  7  9 11]


# linespace

In [8]:

np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

# reshape() 

### use to change dimenstion of array


In [12]:
arr_2d=arr_1d.reshape(2,6) # 2 rows and 6 columns
print(arr_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [15]:
# one to 3d arrayu

arr_3d=arr_1d.reshape(2,3,2)
arr_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [16]:
ar=np.arange(1,13).reshape(2,6)
ar

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [17]:
# ravel convert 3rd dimenstion array to one  dimenstion array 
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten same


In [18]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose()


In [22]:
#  convert row to columns
ar.transpose()
ar.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])