# Python NumPy Array Conctination and Split

In [ ]:
> ### . 1) NumPy concatenate - np.concatenate()
> ### . 2) NumPy vstack - np.vstack()
> ### . 3) NumPy hstack - np.hstack()
> ### . 4) NumPy split - np.split()

In [3]:
import numpy as np 

In [4]:
arr1=np.arange(1,17).reshape(4,4)

In [5]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [6]:
arr2=np.arange(17,33).reshape(4,4)

In [7]:
list1 =[3,2,1]
list2 =[3,3,4]

In [8]:
list1+list2

[3, 2, 1, 3, 3, 4]

In [9]:
arr1 + arr2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [10]:
np.concatenate((arr1,arr2)) # columns wise


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [11]:
print(arr1,arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] [[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [12]:
np.concatenate((arr1,arr2),axis=1) # 1 mean row

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [13]:
np.vstack((arr1,arr2)) # vertical stack

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [14]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [17]:
np.hstack((arr1,arr2,arr1))

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16]])

In [22]:
# cloumns wise split because we have not given  any axis
list1=np.split(arr1,2) # divie array two two parts the output we will get will be list 

In [23]:
type(list1)

list

In [24]:
list1[0] # element inside list is array type 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
type(list1[0])

numpy.ndarray

In [27]:
# axis wise  split 1 mean x - axis 

np.split(arr1,2,axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]), array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]