# Random Sampling with Numpy 


> ### 1. np.random.random()
> ### 2. np.random.randint()
> ### 3. np.random.seed()
> ### 4. np.random.rand()
> ### 5. np.random.randn()
> ### 6. np.random.choice()
> ### 7. np.random.permutation()

In [4]:
import numpy as np 
import random

In [5]:
np.random.random(1)

array([0.07328855])

In [6]:
np.random.random((3,3))

array([[0.95481019, 0.64587509, 0.07936207],
       [0.94895426, 0.62731424, 0.84836873],
       [0.2256138 , 0.75192459, 0.24628569]])

In [8]:
np.random.randint(1,4)

3

In [9]:
np.random.randint(1,4,(4,4))

array([[3, 3, 2, 3],
       [3, 2, 1, 1],
       [1, 3, 2, 3],
       [1, 2, 2, 1]])

In [10]:
np.random.randint(1,4,(2,4,4))

array([[[1, 2, 2, 2],
        [1, 1, 1, 2],
        [1, 2, 3, 2],
        [1, 2, 1, 2]],

       [[1, 2, 1, 2],
        [2, 3, 2, 2],
        [3, 1, 1, 2],
        [1, 2, 3, 3]]])

In [12]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [13]:
2**32-1

4294967295

In [14]:
np.random.rand(3)

array([0.13145815, 0.41366737, 0.77872881])

In [16]:
np.random.randn(3,3)

array([[-1.58494101,  1.05535316, -1.92657911],
       [ 0.69858388, -0.74620143, -0.15662666],
       [-0.19363594,  1.13912535,  0.36221796]])

In [18]:
x=[1,3,2,3]
np.random.choice(x)

1

In [19]:
np.random.choice(x)


1

In [20]:
for i in range(20):
    print(np.random.choice(x))

1
3
1
3
1
1
2
1
2
2
1
3
3
1
3
3
2
2
3
2


In [21]:
np.random.permutation(x)

array([3, 3, 1, 2])

In [22]:
np.random.permutation(x)

array([3, 2, 3, 1])